# Generated by Django 4.0.4 on 2022-05-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=10)),
                ('start_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('end_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=5)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords_text', models.CharField(max_length=30)),
                ('importance', models.FloatField()),
                ('related_stocks', models.CharField(max_length=30)),
                ('summarized_text', models.CharField(max_length=200)),
                ('news_title_1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('news_url_1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('news_title_2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('news_url_2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('news_title_3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('news_url_3', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_code', models.CharField(max_length=10)),
                ('market_cap', models.IntegerField()),
                ('change_rate', models.FloatField()),
            ],
        ),
    ]
